# Generated by Django 6.0.3 on 2026-04-08 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_size', models.PositiveSmallIntegerField()),
                ('workspace_state', models.JSONField(default=dict)),
                ('is_submitted', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_groups', to='exercises.exercise')),
            ],
            options={
                'db_table': 'collaboration_collab_group',
            },
        ),
        migrations.CreateModel(
            name='CollabSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_answer', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='collaboration.collabgroup')),
            ],
            options={
                'db_table': 'collaboration_collab_submission',
            },
        ),
        migrations.CreateModel(
            name='CollabGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_contribution_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collaboration.collabgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_collab_group_member',
                'unique_together': {('group', 'student')},
            },
        ),
    ]
