/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as TeacherAnalyticsCourseIdRouteImport } from './routes/teacher/analytics/$courseId'
import { Route as CoursesCourseIdForumRouteImport } from './routes/courses/$courseId/forum'
import { Route as CoursesCourseIdChatRouteImport } from './routes/courses/$courseId/chat'
import { Route as TeacherCoursesCourseIdBuilderRouteImport } from './routes/teacher/courses/$courseId/builder'
import { Route as CoursesCourseIdLessonsLessonIdRouteImport } from './routes/courses/$courseId/lessons/$lessonId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAnalyticsCourseIdRoute =
  TeacherAnalyticsCourseIdRouteImport.update({
    id: '/teacher/analytics/$courseId',
    path: '/teacher/analytics/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseIdForumRoute = CoursesCourseIdForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdChatRoute = CoursesCourseIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const TeacherCoursesCourseIdBuilderRoute =
  TeacherCoursesCourseIdBuilderRouteImport.update({
    id: '/teacher/courses/$courseId/builder',
    path: '/teacher/courses/$courseId/builder',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseIdLessonsLessonIdRoute =
  CoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/courses/$courseId/chat': typeof CoursesCourseIdChatRoute
  '/courses/$courseId/forum': typeof CoursesCourseIdForumRoute
  '/teacher/analytics/$courseId': typeof TeacherAnalyticsCourseIdRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
  '/teacher/courses/$courseId/builder': typeof TeacherCoursesCourseIdBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/courses/$courseId/chat': typeof CoursesCourseIdChatRoute
  '/courses/$courseId/forum': typeof CoursesCourseIdForumRoute
  '/teacher/analytics/$courseId': typeof TeacherAnalyticsCourseIdRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
  '/teacher/courses/$courseId/builder': typeof TeacherCoursesCourseIdBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/courses/$courseId/chat': typeof CoursesCourseIdChatRoute
  '/courses/$courseId/forum': typeof CoursesCourseIdForumRoute
  '/teacher/analytics/$courseId': typeof TeacherAnalyticsCourseIdRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
  '/teacher/courses/$courseId/builder': typeof TeacherCoursesCourseIdBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/courses/$courseId'
    | '/projects/$projectId'
    | '/courses/'
    | '/dashboard/'
    | '/profile/'
    | '/projects/'
    | '/teacher/'
    | '/courses/$courseId/chat'
    | '/courses/$courseId/forum'
    | '/teacher/analytics/$courseId'
    | '/courses/$courseId/lessons/$lessonId'
    | '/teacher/courses/$courseId/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/courses/$courseId'
    | '/projects/$projectId'
    | '/courses'
    | '/dashboard'
    | '/profile'
    | '/projects'
    | '/teacher'
    | '/courses/$courseId/chat'
    | '/courses/$courseId/forum'
    | '/teacher/analytics/$courseId'
    | '/courses/$courseId/lessons/$lessonId'
    | '/teacher/courses/$courseId/builder'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/courses/$courseId'
    | '/projects/$projectId'
    | '/courses/'
    | '/dashboard/'
    | '/profile/'
    | '/projects/'
    | '/teacher/'
    | '/courses/$courseId/chat'
    | '/courses/$courseId/forum'
    | '/teacher/analytics/$courseId'
    | '/courses/$courseId/lessons/$lessonId'
    | '/teacher/courses/$courseId/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherAnalyticsCourseIdRoute: typeof TeacherAnalyticsCourseIdRoute
  TeacherCoursesCourseIdBuilderRoute: typeof TeacherCoursesCourseIdBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/analytics/$courseId': {
      id: '/teacher/analytics/$courseId'
      path: '/teacher/analytics/$courseId'
      fullPath: '/teacher/analytics/$courseId'
      preLoaderRoute: typeof TeacherAnalyticsCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/forum': {
      id: '/courses/$courseId/forum'
      path: '/forum'
      fullPath: '/courses/$courseId/forum'
      preLoaderRoute: typeof CoursesCourseIdForumRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/chat': {
      id: '/courses/$courseId/chat'
      path: '/chat'
      fullPath: '/courses/$courseId/chat'
      preLoaderRoute: typeof CoursesCourseIdChatRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/teacher/courses/$courseId/builder': {
      id: '/teacher/courses/$courseId/builder'
      path: '/teacher/courses/$courseId/builder'
      fullPath: '/teacher/courses/$courseId/builder'
      preLoaderRoute: typeof TeacherCoursesCourseIdBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/lessons/$lessonId': {
      id: '/courses/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof CoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdChatRoute: typeof CoursesCourseIdChatRoute
  CoursesCourseIdForumRoute: typeof CoursesCourseIdForumRoute
  CoursesCourseIdLessonsLessonIdRoute: typeof CoursesCourseIdLessonsLessonIdRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdChatRoute: CoursesCourseIdChatRoute,
  CoursesCourseIdForumRoute: CoursesCourseIdForumRoute,
  CoursesCourseIdLessonsLessonIdRoute: CoursesCourseIdLessonsLessonIdRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherAnalyticsCourseIdRoute: TeacherAnalyticsCourseIdRoute,
  TeacherCoursesCourseIdBuilderRoute: TeacherCoursesCourseIdBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
